<?php
// ACF Settings
class ACF_Settings
{
    public function __construct()
    {
        $this -> bc_menu_acf();
    }

    private function bc_menu_acf()
    {
        if( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_5d1a48aa09f78',
                'title' => 'Plugin: BC Menu',
                'fields' => array(
                    array(
                        'key' => 'field_5d42ee4eadcf5',
                        'label' => 'Hero Section',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5d42ee87adcf6',
                        'label' => 'Hero Background Image',
                        'name' => 'menu_hero_background_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5d42eed7adcf7',
                        'label' => 'Centered Image',
                        'name' => 'menu_centered_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5d42eef6adcf8',
                        'label' => 'Hero Title',
                        'name' => 'menu_hero_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d42ef14adcf9',
                        'label' => 'Hero Sub Title',
                        'name' => 'menu_hero_sub_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d2365986246f',
                        'label' => 'Menu Layouts',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5d1f54706a172',
                        'label' => 'Menu Display Options',
                        'name' => 'menu_options',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5fdbc103f85f3',
                                'label' => 'Display Prices With Line Break',
                                'name' => 'display_prices_with_line_break',
                                'type' => 'true_false',
                                'instructions' => 'Default is |',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => '',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5d1a5f32c97c7',
                                'label' => 'Full Width Menu',
                                'name' => 'full_width_menu',
                                'type' => 'true_false',
                                'instructions' => 'Make menu full width to extend out (default: contained).',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => 'Toggle Full Width On',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5d1bb87c11f3a',
                                'label' => 'Center Align Description and Title Toggle',
                                'name' => 'center_align_text',
                                'type' => 'true_false',
                                'instructions' => 'Center align title and description text on all items. (Default: Left Align)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => 'Toggle Center Alignment On',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                            array(
                                'key' => 'field_5d1f6c7319eb5',
                                'label' => 'Item Image Layout Toggle',
                                'name' => 'featured_image',
                                'type' => 'true_false',
                                'instructions' => 'Toggle the ability to add an image to each item',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '33',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => 'Toggle Item Images On',
                                'default_value' => 0,
                                'ui' => 1,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d2365aa62470',
                        'label' => 'Menu Navigation Options',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5d1cf8c751999',
                        'label' => 'Navigation Options',
                        'name' => 'navigation_options',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d1bb11187107',
                                'label' => 'Top Standard Category Nav Bar',
                                'name' => 'top_bar',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d1f97a1e62b6',
                                        'label' => 'Toggle On/Off',
                                        'name' => 'turn_on',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Enable (On)',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d238589c0f07',
                                        'label' => 'Make Sticky',
                                        'name' => 'sticky',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Toggle Sticky on/off',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f97b9e62b7',
                                        'label' => 'Desktop Visibility',
                                        'name' => 'desktop',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Desktop',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f97c9e62b8',
                                        'label' => 'Tablet Visibility',
                                        'name' => 'tablet',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Tablet',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f97d6e62b9',
                                        'label' => 'Mobile Visibility',
                                        'name' => 'mobile',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Mobile',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d1cc72185898',
                                'label' => 'Drop Down Top Menu',
                                'name' => 'drop_down_top_menu',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d1f7f54130ee',
                                        'label' => 'Toggle On/Off',
                                        'name' => 'turn_on',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Enable (On)',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d23a8a4d2589',
                                        'label' => 'Make Sticky',
                                        'name' => 'sticky',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Toggle Sticky on/off',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f7f79130ef',
                                        'label' => 'Desktop Visibility',
                                        'name' => 'desktop',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Desktop',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f7f96130f0',
                                        'label' => 'Tablet Visibility',
                                        'name' => 'tablet',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Tablet',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f7fae130f1',
                                        'label' => 'Mobile Visibility',
                                        'name' => 'mobile',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Mobile',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d1bbf48d742c',
                                'label' => 'Bottom Sticky Menu',
                                'name' => 'bottom_sticky_menu',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_5d1f88d566473',
                                        'label' => 'Toggle On/Off',
                                        'name' => 'turn_on',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Enable (On)',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f88e466474',
                                        'label' => 'Desktop Visibility',
                                        'name' => 'desktop',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Desktop',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f890966476',
                                        'label' => 'Tablet Visibility',
                                        'name' => 'tablet',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Tablet',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f891a66477',
                                        'label' => 'Mobile Visibility',
                                        'name' => 'mobile',
                                        'type' => 'true_false',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'message' => 'Show on Mobile',
                                        'default_value' => 0,
                                        'ui' => 0,
                                        'ui_on_text' => '',
                                        'ui_off_text' => '',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d1cfcdf3a7b0',
                                'label' => 'Side Bar',
                                'name' => 'side_bar',
                                'type' => 'true_false',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'message' => 'Enable Sidebar (On)',
                                'default_value' => 0,
                                'ui' => 0,
                                'ui_on_text' => '',
                                'ui_off_text' => '',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_5d2365bc62471',
                        'label' => 'Menu',
                        'name' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_5d1a48af28d9c',
                        'label' => 'Menu Group',
                        'name' => 'menu_group',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_5d1a490b28d9d',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'block',
                        'button_label' => '',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_5d1a490b28d9d',
                                'label' => 'Menu Group Title',
                                'name' => 'menu_group_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '50',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array(
                                'key' => 'field_5d1a4c0f8d07e',
                                'label' => 'Menu Group Background Image',
                                'name' => 'menu_group_background_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'preview_size' => 'medium',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array(
                                'key' => 'field_5d1a4c258d07f',
                                'label' => 'Menu Items Per Row',
                                'name' => 'menu_items_per_row',
                                'type' => 'button_group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'col-lg-12' => '1',
                                    'col-lg-6' => '2',
                                    'col-lg-4' => '3',
                                    'col-lg-3' => '4',
                                ),
                                'allow_null' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ),
                            array(
                                'key' => 'field_5d1a491728d9e',
                                'label' => 'Menu Group Description',
                                'name' => 'menu_group_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 8,
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_5d1a493d28d9f',
                                'label' => 'Menu Item',
                                'name' => 'menu_item',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'block',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_60491f6776dbe',
                                        'label' => 'Menu Sub Group Title',
                                        'name' => 'menu_sub_group_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_60491e12001a0',
                                        'label' => 'Menu Item Class',
                                        'name' => 'menu_item_class',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1f734d3e8c3',
                                        'label' => 'Menu Item Featured Image',
                                        'name' => 'menu_item_featured_image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array(
                                            array(
                                                array(
                                                    'field' => 'field_5d1f6c7319eb5',
                                                    'operator' => '==',
                                                    'value' => '1',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1a495828da0',
                                        'label' => 'Menu Item Title',
                                        'name' => 'menu_item_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_5d1a4a28317fe',
                                        'label' => 'Menu Item Size and Price',
                                        'name' => 'menu_item_size_and_price',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '33',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'collapsed' => '',
                                        'min' => 0,
                                        'max' => 0,
                                        'layout' => 'table',
                                        'button_label' => '',
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_5d1a4a9829a64',
                                                'label' => 'Item Size',
                                                'name' => 'item_size',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                            array(
                                                'key' => 'field_5d1a4a9d29a65',
                                                'label' => 'Item Price',
                                                'name' => 'item_price',
                                                'type' => 'text',
                                                'instructions' => '',
                                                'required' => 0,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'default_value' => '',
                                                'placeholder' => '',
                                                'prepend' => '',
                                                'append' => '',
                                                'maxlength' => '',
                                            ),
                                        ),
                                    ),
                                    array(
                                        'key' => 'field_5fdb8683796e4',
                                        'label' => 'Menu Item Dietary Options',
                                        'name' => 'menu_item_dietary_options',
                                        'type' => 'checkbox',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'v' => 'Vegan',
                                            'vg' => 'Vegetarian',
                                            'gf' => 'Gluten Free',
                                        ),
                                        'allow_custom' => 0,
                                        'default_value' => array(
                                        ),
                                        'layout' => 'horizontal',
                                        'toggle' => 0,
                                        'return_format' => 'value',
                                        'save_custom' => 0,
                                    ),
                                    array(
                                        'key' => 'field_5d1a4aa729a66',
                                        'label' => 'Menu Item Description',
                                        'name' => 'menu_item_description',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 4,
                                        'new_lines' => 'br',
                                    ),
                                ),
                            ),
                            array(
                                'key' => 'field_5d4205865df1f',
                                'label' => 'Warning or Allergies',
                                'name' => 'warning_or_allergies',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => 4,
                                'new_lines' => 'br',
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => 'menus',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
            ));
            
        endif;
    }
}
